name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  security-events: write
  actions: read
  checks: write
  pull-requests: write

env:
  NODE_VERSION: '18'
  CACHE_KEY_PREFIX: 'haas-v1'

jobs:
  setup:
    name: Setup and Cache Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-deps.outputs.cache-hit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ env.CACHE_KEY_PREFIX }}-deps-${{ runner.os }}-node${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ env.CACHE_KEY_PREFIX }}-deps-${{ runner.os }}-node${{ env.NODE_VERSION }}-

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci

  lint-and-typecheck:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ env.CACHE_KEY_PREFIX }}-deps-${{ runner.os }}-node${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: needs.setup.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript type check
        run: npm run type-check

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        test-group: [unit, integration]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ env.CACHE_KEY_PREFIX }}-deps-${{ runner.os }}-node${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: needs.setup.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run unit tests
        if: matrix.test-group == 'unit'
        run: npm run test:unit -- --coverage --coverageReporters=json --passWithNoTests
        env:
          NEXT_PUBLIC_SUPABASE_URL: https://test.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: test-anon-key
          SUPABASE_SERVICE_ROLE_KEY: test-service-role-key
          LINE_CHANNEL_SECRET: test-line-secret
          LINE_CHANNEL_ACCESS_TOKEN: test-line-token
          APP_BASE_URL: http://localhost:3000

      - name: Run integration tests
        if: matrix.test-group == 'integration'
        run: npm run test:integration -- --coverage --coverageReporters=json --passWithNoTests
        env:
          NEXT_PUBLIC_SUPABASE_URL: https://test.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: test-anon-key
          SUPABASE_SERVICE_ROLE_KEY: test-service-role-key
          LINE_CHANNEL_SECRET: test-line-secret
          LINE_CHANNEL_ACCESS_TOKEN: test-line-token
          APP_BASE_URL: http://localhost:3000

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.test-group }}
          path: coverage/coverage-final.json

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium]
        shard: [1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ env.CACHE_KEY_PREFIX }}-deps-${{ runner.os }}-node${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: needs.setup.outputs.cache-hit != 'true'
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: .

      - name: Extract build artifacts
        run: |
          echo "Extracting build artifacts..."
          tar -xzf build-artifact.tar.gz
          echo "Extraction complete. Contents:"
          ls -la .next | head -10

      - name: Install Playwright browsers
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: Run E2E tests
        run: npm run test:e2e:ci -- --project=${{ matrix.browser }}
        env:
          CI: true
          NODE_ENV: production
          PLAYWRIGHT_BASE_URL: http://localhost:3000
          NEXT_PUBLIC_SUPABASE_URL: https://test.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: test-anon-key
          SUPABASE_SERVICE_ROLE_KEY: test-service-role-key
          LINE_CHANNEL_SECRET: test-line-secret
          LINE_CHANNEL_ACCESS_TOKEN: test-line-token
          APP_BASE_URL: http://localhost:3000
          E2E_USE_REAL_BACKEND: false

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 30

  coverage-report:
    name: Coverage Report
    runs-on: ubuntu-latest
    needs: [unit-tests]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./coverage-artifacts

      - name: Merge coverage reports
        run: |
          mkdir -p coverage
          # Merge coverage reports from different test groups
          npx nyc merge coverage-artifacts coverage/merged-coverage.json
          npx nyc report --reporter=lcov --reporter=text --reporter=html --temp-dir coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: haas-coverage
          fail_ci_if_error: false

      - name: Coverage comment
        uses: 5monkeys/cobertura-action@master
        if: github.event_name == 'pull_request'
        with:
          path: coverage/cobertura-coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 70
          fail_below_threshold: true

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck, unit-tests]
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ env.CACHE_KEY_PREFIX }}-deps-${{ runner.os }}-node${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: needs.setup.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build application
        run: |
          echo "=== Build Debug Information ==="
          echo "Current directory: $(pwd)"
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo ""
          echo "=== Package.json build script ==="
          grep '"build"' package.json
          echo ""
          echo "=== Files before build ==="
          ls -la | head -20
          echo ""
          echo "=== Running build command ==="
          npm run build 2>&1 | tee build.log
          BUILD_EXIT_CODE=${PIPESTATUS[0]}
          echo ""
          echo "=== Build exit code: $BUILD_EXIT_CODE ==="
          if [ $BUILD_EXIT_CODE -ne 0 ]; then
            echo "❌ Build FAILED!"
            echo "Last 50 lines of build output:"
            tail -50 build.log
            exit $BUILD_EXIT_CODE
          fi
          echo "✅ Build completed successfully"
          echo ""
          echo "=== Files after build ==="
          ls -la | head -20
          echo ""
          echo "=== Checking for .next directory ==="
          if [ -d ".next" ]; then
            echo "✅ .next directory exists"
            echo "Size: $(du -sh .next)"
          else
            echo "❌ .next directory does NOT exist!"
          fi
        env:
          NEXT_PUBLIC_SUPABASE_URL: https://placeholder.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: placeholder-key

      - name: Verify build output
        run: |
          echo "Checking current directory..."
          pwd
          echo "Listing all directories..."
          ls -la
          echo "Checking for .next directory..."
          if [ -d ".next" ]; then
            echo ".next directory exists!"
            ls -la .next/ | head -10
            echo "Build directory size:"
            du -sh .next/
          else
            echo "❌ .next directory NOT found after build"
            echo "Checking if build created output elsewhere..."
            find . -type d -name ".next" 2>/dev/null || echo "No .next found anywhere"
          fi

      - name: Prepare artifacts for upload
        run: |
          echo "=== Preparing artifacts for upload ==="
          if [ ! -d ".next" ]; then
            echo "❌ ERROR: .next directory does not exist!"
            exit 1
          fi
          echo "✅ .next directory exists"
          echo "Creating tar archive..."
          tar -czf build-artifact.tar.gz .next
          echo "Archive created: $(ls -lh build-artifact.tar.gz)"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build-artifact.tar.gz
          retention-days: 7
          if-no-files-found: error

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ env.CACHE_KEY_PREFIX }}-deps-${{ runner.os }}-node${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: needs.setup.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck, unit-tests, build, security-scan, e2e-tests]
    if: always()
    steps:
      - name: Check test results
        run: |
          echo "Lint and typecheck: ${{ needs.lint-and-typecheck.result }}"
          echo "Unit tests: ${{ needs.unit-tests.result }}"
          echo "Build: ${{ needs.build.result }}"
          echo "Security scan: ${{ needs.security-scan.result }}"
          echo "E2E tests: ${{ needs.e2e-tests.result }}"

          if [[ "${{ needs.lint-and-typecheck.result }}" != "success" ]]; then
            echo "❌ Lint and typecheck failed"
            exit 1
          fi

          if [[ "${{ needs.unit-tests.result }}" != "success" ]]; then
            echo "❌ Unit tests failed"
            exit 1
          fi

          if [[ "${{ needs.build.result }}" != "success" ]]; then
            echo "❌ Build failed"
            exit 1
          fi

          if [[ "${{ needs.e2e-tests.result }}" != "success" ]]; then
            echo "❌ E2E tests failed"
            exit 1
          fi

          if [[ "${{ needs.security-scan.result }}" != "success" ]]; then
            echo "⚠️ Security scan failed (non-blocking)"
          fi

          echo "✅ All quality gates passed"

  notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [quality-gates, e2e-tests]
    if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    steps:
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#haas-ci'
          text: |
            Build ${{ job.status }} for ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}